<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AssemblyName>KlasorKasa</AssemblyName>
    <RootNamespace>KlasorKasa</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\KlasorKasa-v2.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <Company>ERDSoft</Company>
    <Product>KlasörKasa</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="KlasorKasa.Tests\**\*.cs" />
    <None Remove="KlasorKasa.Tests\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Brand\KlasorKasaMark.png" />
  </ItemGroup>
</Project>
